language: go
go:
- 1.7.x
script:
- 'if [ "${JOB}" = "test" ]; then make unit_tests; fi'
- 'if [ "${JOB}" = "build" ]; then make image; fi'
env:
    global:
        - GOARCH=amd64
matrix:
    - JOB=test
    - JOB=build
notifications:
    email:
        on_success: change
        on_failure: always
